service: javalambda

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: lab

package:
  artifact: target/javalambda.jar

functions:
  hello:
    handler: com.serverless.Hello
    events:
      - http:
          path: hello
          method: get
