service: dotnetlambda

provider:
  name: aws
  runtime: dotnetcore3.1
  region: us-east-1
  stage: lab

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/release/netcoreapp3.1/hello.zip
    events:
      - http:
          path: hello
          method: get
          cors: true
          integration: LAMBDA 
